### PR TITLE
Configure plugins externally

### PR DESCRIPTION
**Pull request by tarcisiozf**
This is required for the hosted version.

depends on: https://github.com/bitfinexcom/bfx-api-node-core/pull/20

### CODE REVIEW

**Review by avsek477 — APPROVED** [review]
lgtm

**Review by vitaliystoliarovcc — APPROVED** [review]
lgtm

**Review by robertkowalski — APPROVED** [review]
lgtm

**Comment by robertkowalski** [comment]
(will merge after next release)

**Pull request merged**
