### PR TITLE
skip outdated ma values for order price calculation

### PR DESCRIPTION
**Pull request by avsek477**
- Skips the ma calculated values from outdated candles

### CODE REVIEW

**Review by tarcisiozf — APPROVED** [review]
I'm guessing that we don't have good test coverage for this so this why there are no test changes.

**Review by vitaliystoliarovcc — APPROVED** [review]
lgtm

**Review by tarcisiozf — APPROVED** [review]
lgtm

**Review by robertkowalski — APPROVED** [review]
lgtm

**Pull request merged**
