### PR TITLE
Benchmark fixes

### PR DESCRIPTION
**Pull request by vitaliystoliarovcc**
This PR is created primarily to improve the benchmark system in order to more easily localize memory leaks.

The main change is waiting and forcing the memory cleanup, since it can't be performed immediately after the operations have been called.

### CODE REVIEW

**Comment by vitaliystoliarovcc** [comment]
`submit_order`

1. `npm run benchmark:mock`
2. `TARGET=submit_order npm run benchmark:debug`
3. Open DevTools and take snapshot
4. `autocannon -d 10 localhost:3000` 
5. Take snapshot
6. Run `curl "localhost:3000/gc?interval=5&iterations=10"` 4-5 times
7. Take snapshot

Result:
autocannon produced 2k requests
image
image

Despite the fact that the memory is cleaned only after a few minutes, this does not happen completely and for 2k requests there is a 7 MB leak

**Comment by tarcisiozf** [comment]
lgtm

**Review by tarcisiozf — APPROVED** [review]
lgtm

**Comment by avsek477** [comment]
@vitaliystoliarovcc can you also remove these events `ao:start` and `ao:stop` since we don't have them anymore.

https://github.com/bitfinexcom/bfx-hf-algo/blob/d58d7ba3e108e41aa1d4bc99942533fc75954503/benchmarks/fixtures/host.js#L21 

otherwise, lgtm

**Review by avsek477 — APPROVED** [review]

**Review by robertkowalski — APPROVED** [review]
lgtm

**Pull request merged**
