### PR TITLE
Remove OCO delay

### PR DESCRIPTION
**Pull request by vitaliystoliarovcc**
Asana ticket: https://app.asana.com/0/1125859137800433/1200174906704560/f

### CODE REVIEW

**Review by avsek477 — APPROVED** [review]
lgtm

**Comment by robertkowalski** [comment]
```
/Users/robert/bitfinex/bfx-hf-algo/lib/ococo/meta/process_params.js:
   25    }
   26  
   27:   if (params.submitDelaySec) {
   28:     params.submitDelay = params.submitDelaySec * 1000
   29:     delete params.submitDelaySec
   30    }
   31  
   32:   if (!_isFinite(params.submitDelay)) {
   33:     params.submitDelay = 2000
   34    }
   35  
   ```

**Comment by robertkowalski** [comment]
```
/Users/robert/bitfinex/bfx-hf-algo/lib/ococo/meta/validate_params.js:
   23   * @param {number} args.ocoAmount - oco order amount
   24   * @param {string} args.ocoAction - oco order direction, Buy or Sell
   25:  * @param {number} args.submitDelaySec - submit delay in seconds
   26   * @returns {string} error - null if parameters are valid, otherwise a
   27   *   description of which parameter is invalid.
   ..
   29  const validateParams = (args = {}) => {
   30    const {
   31:     orderPrice, amount, orderType, submitDelay, limitPrice,
   32      stopPrice, ocoAmount, lev, _futures, action, ocoAction
   33    } = args
   ..
   35    if (!_includes(ORDER_TYPES, orderType)) return `Invalid order type: ${orderType}`
   36    if (!_isFinite(amount)) return 'Invalid amount'
   37:   if (!_isFinite(submitDelay) || submitDelay < 0) return 'Invalid submit delay'
```

**Review by robertkowalski — CHANGES_REQUESTED** [review]
found two leftovers

**Review by robertkowalski — APPROVED** [review]
lgtm

**Pull request merged**
